# Generated by Django 4.1.7 on 2023-04-06 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='borrower_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrower_id', models.IntegerField(editable=False, unique=True)),
                ('name', models.CharField(max_length=20, null=True, unique=True)),
                ('completed_loans', models.IntegerField(default=0)),
                ('active_loans', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='loan_manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_balance', models.IntegerField(default=0)),
                ('ongoing', models.IntegerField(default=0)),
                ('profit', models.IntegerField(default=0)),
                ('current', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='loan_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_id', models.IntegerField(editable=False, unique=True)),
                ('loan_type', models.CharField(choices=[('monthly', 'Monthly'), ('daily', 'Daily')], max_length=8)),
                ('name', models.CharField(max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('amount_loan', models.IntegerField()),
                ('total_days', models.IntegerField()),
                ('start_date', models.DateField(null=True)),
                ('due_date', models.DateField(null=True)),
                ('paid_days', models.IntegerField(default=0)),
                ('days_left', models.IntegerField(default=0)),
                ('paid_amount', models.IntegerField(default=0)),
                ('amount_per_day', models.IntegerField()),
                ('amount_left', models.IntegerField()),
                ('progress', models.IntegerField(default=0)),
                ('status', models.CharField(default='incomplete', max_length=15)),
                ('renew_count', models.IntegerField(default=0)),
                ('loan_profit', models.IntegerField(default=0)),
                ('tata_profit', models.IntegerField(default=0)),
                ('is_approved', models.BooleanField(default=False)),
                ('staff', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='payment_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.CharField(max_length=20, null=True)),
                ('amount', models.IntegerField()),
                ('dates_request', models.TextField(max_length=500, null=True)),
                ('date_approved', models.DateField(null=True)),
                ('borrower_name', models.CharField(max_length=20, null=True)),
                ('loan_id', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='staff_manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.CharField(max_length=20, null=True, unique=True)),
                ('amount', models.IntegerField(default=0)),
                ('date_requested', models.DateField(null=True)),
                ('date_approved', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='loan_payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dates_to_pay', models.DateField(null=True)),
                ('paid_dates', models.DateField(null=True)),
                ('paid', models.BooleanField(default=False)),
                ('isAudit', models.BooleanField(default=False)),
                ('staff', models.CharField(max_length=20, null=True, unique=True)),
                ('loan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loanmanager.loan_table')),
            ],
        ),
    ]
