# Generated by Django 4.1.7 on 2023-04-06 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loanmanager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan_table',
            old_name='tata_profit',
            new_name='staff_profit',
        ),
    ]
