# Generated by Django 4.1.7 on 2023-04-09 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanmanager', '0002_rename_tata_profit_loan_table_staff_profit'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_request',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payment_request',
            name='request_date',
            field=models.DateField(null=True),
        ),
    ]
