# Generated by Django 4.1.7 on 2023-04-09 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanmanager', '0003_payment_request_is_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_request',
            name='request_number',
            field=models.IntegerField(editable=False, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='payment_request',
            name='amount',
            field=models.IntegerField(null=True),
        ),
    ]
