# Generated by Django 4.1.7 on 2023-04-10 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanmanager', '0004_payment_request_request_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan_payment',
            name='staff',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
