# Generated by Django 4.1.7 on 2023-04-26 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanmanager', '0007_alter_loan_table_amount_left_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_balance', models.IntegerField(null=True)),
                ('active_loans', models.IntegerField(null=True)),
                ('available_balance', models.IntegerField(null=True)),
                ('active_borrowers', models.IntegerField(null=True)),
            ],
        ),
    ]
