# Generated by Django 4.1.7 on 2023-04-26 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanmanager', '0008_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='name',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
