# Generated by Django 4.1.7 on 2023-04-26 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanmanager', '0009_bank_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='active_borrowers',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='bank',
            name='active_loans',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='bank',
            name='available_balance',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='bank',
            name='total_balance',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
