# Generated by Django 4.1.7 on 2023-04-27 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanmanager', '0010_alter_bank_active_borrowers_alter_bank_active_loans_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(default=0)),
                ('balance', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='loan_manager',
        ),
    ]
