# Generated by Django 4.1.7 on 2023-04-27 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanmanager', '0011_staff_delete_loan_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='name',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
