# Generated by Django 4.1.7 on 2023-04-29 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanmanager', '0013_staff_total_profit'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_request',
            name='completion',
            field=models.BooleanField(default=False),
        ),
    ]
