# Generated by Django 4.1.7 on 2023-04-29 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loanmanager', '0014_payment_request_completion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bank',
            old_name='total_balance',
            new_name='earnings',
        ),
    ]
