# Generated by Django 4.1.7 on 2023-04-29 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loanmanager', '0015_rename_total_balance_bank_earnings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank',
            name='active_borrowers',
        ),
        migrations.RemoveField(
            model_name='bank',
            name='active_loans',
        ),
    ]
