# Generated by Django 4.1.7 on 2023-04-29 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanmanager', '0016_remove_bank_active_borrowers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='active_amount',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
