# Generated by Django 4.1.7 on 2023-02-24 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='borrower_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrowerId', models.IntegerField(max_length=6, unique=True)),
                ('name', models.CharField(max_length=20)),
                ('completedLoans', models.IntegerField(default=0)),
                ('activeLoans', models.IntegerField(default=0)),
            ],
        ),
    ]
