# Generated by Django 4.1.7 on 2023-02-24 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='loan_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loanId', models.IntegerField(editable=False, max_length=6, unique=True)),
                ('loanType', models.CharField(choices=[('M', 'Monthly'), ('D', 'Daily')], max_length=8)),
                ('name', models.CharField(choices=[('test_borrower1', 'test_borrower1')], max_length=20)),
                ('isActive', models.BooleanField(default=True)),
                ('amountLoan', models.IntegerField(max_length=6)),
                ('totalDays', models.IntegerField(max_length=3)),
                ('startDate', models.DateField()),
                ('dueDate', models.DateField()),
                ('paidDays', models.IntegerField(max_length=3)),
                ('daysLeft', models.IntegerField(max_length=3)),
            ],
        ),
        migrations.AlterField(
            model_name='borrower_table',
            name='borrowerId',
            field=models.IntegerField(editable=False, max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='borrower_table',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
