# Generated by Django 4.1.7 on 2023-02-24 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0002_loan_table_alter_borrower_table_borrowerid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan_table',
            name='amountLoan',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='loan_table',
            name='daysLeft',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='loan_table',
            name='paidDays',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='loan_table',
            name='totalDays',
            field=models.IntegerField(),
        ),
    ]
