# Generated by Django 4.1.7 on 2023-02-24 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0004_loan_table_amountperday_loan_table_paidamount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan_table',
            name='amountPerDay',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='loan_table',
            name='paidAmount',
            field=models.IntegerField(),
        ),
    ]
