# Generated by Django 4.1.7 on 2023-02-24 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0006_loan_table_paiddates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan_table',
            name='paidDates',
            field=models.TextField(),
        ),
    ]
