# Generated by Django 4.1.7 on 2023-02-25 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0007_alter_loan_table_paiddates'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan_table',
            name='amountLeft',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='loan_table',
            name='progress',
            field=models.IntegerField(default=0),
        ),
    ]
