# Generated by Django 4.1.7 on 2023-02-25 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0009_alter_loan_table_amountleft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan_table',
            name='loanType',
            field=models.CharField(choices=[('Monthly', 'Monthly'), ('Daily', 'Daily')], max_length=8),
        ),
    ]
