# Generated by Django 4.1.7 on 2023-02-25 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0010_alter_loan_table_loantype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan_table',
            name='loanType',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('daily', 'Daily')], max_length=8),
        ),
    ]
