# Generated by Django 4.1.7 on 2023-02-25 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0011_alter_loan_table_loantype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan_table',
            name='name',
            field=models.CharField(choices=[('test_borrower2', 'test_borrower2'), ('test_borrower3', 'test_borrower3'), ('test_borrower1', 'test_borrower1'), ('Cris/Elvie', 'Cris/Elvie'), ('GIna', 'GIna'), ('Edward', 'Edward')], max_length=20),
        ),
    ]
