# Generated by Django 4.1.7 on 2023-02-25 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0012_alter_loan_table_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan_table',
            name='status',
            field=models.CharField(default='incomplete', max_length=15),
        ),
        migrations.AlterField(
            model_name='loan_table',
            name='name',
            field=models.CharField(choices=[('Cris/Elvie', 'Cris/Elvie'), ('GIna', 'GIna'), ('Edward', 'Edward')], max_length=20),
        ),
    ]
