# Generated by Django 4.1.7 on 2023-02-25 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0014_alter_borrower_table_borrowerid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan_table',
            name='name',
            field=models.CharField(choices=[('Cris/Elvie', 'Cris/Elvie'), ('Edward', 'Edward'), ('Gina', 'Gina'), ('Dodong', 'Dodong'), ('Totoy/Tess', 'Totoy/Tess'), ('Jun', 'Jun'), ('August', 'August'), ('Manners', 'Manners'), ('Joy', 'Joy'), ('Charlie', 'Charlie'), ('Grace', 'Grace'), ('Oman', 'Oman'), ('Nhot', 'Nhot'), ('Eden', 'Eden'), ('Totoy/Marie', 'Totoy/Marie'), ('Horges', 'Horges'), ('Roel', 'Roel'), ('Kiko', 'Kiko'), ('Nomer', 'Nomer'), ('Randel', 'Randel'), ('Cris', 'Cris'), ('Paz', 'Paz'), ('Norman', 'Norman'), ('Paglas', 'Paglas'), ('Yogi', 'Yogi'), ('Shirley', 'Shirley'), ('Baby/Jo', 'Baby/Jo'), ('Len2', 'Len2'), ('Jun2/Asawa', 'Jun2/Asawa')], default=[('Cris/Elvie', 'Cris/Elvie'), ('Edward', 'Edward'), ('Gina', 'Gina'), ('Dodong', 'Dodong'), ('Totoy/Tess', 'Totoy/Tess'), ('Jun', 'Jun'), ('August', 'August'), ('Manners', 'Manners'), ('Joy', 'Joy'), ('Charlie', 'Charlie'), ('Grace', 'Grace'), ('Oman', 'Oman'), ('Nhot', 'Nhot'), ('Eden', 'Eden'), ('Totoy/Marie', 'Totoy/Marie'), ('Horges', 'Horges'), ('Roel', 'Roel'), ('Kiko', 'Kiko'), ('Nomer', 'Nomer'), ('Randel', 'Randel'), ('Cris', 'Cris'), ('Paz', 'Paz'), ('Norman', 'Norman'), ('Paglas', 'Paglas'), ('Yogi', 'Yogi'), ('Shirley', 'Shirley'), ('Baby/Jo', 'Baby/Jo'), ('Len2', 'Len2'), ('Jun2/Asawa', 'Jun2/Asawa')], max_length=20),
        ),
    ]
