# Generated by Django 4.1.7 on 2023-03-01 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0015_alter_loan_table_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan_table',
            name='loanProfit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='loan_table',
            name='renewCount',
            field=models.IntegerField(default=0),
        ),
    ]
