# Generated by Django 4.1.7 on 2023-03-01 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0016_loan_table_loanprofit_loan_table_renewcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan_table',
            name='tataProfit',
            field=models.IntegerField(default=0),
        ),
    ]
