# Generated by Django 4.1.7 on 2023-03-02 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0017_loan_table_tataprofit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan_table',
            name='startDate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
