# Generated by Django 4.1.7 on 2023-03-04 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0018_alter_loan_table_startdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan_table',
            name='isApproved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='loan_table',
            name='paidAmount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='loan_table',
            name='paidDates',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='loan_table',
            name='paidDays',
            field=models.IntegerField(default=0),
        ),
    ]
