# Generated by Django 4.1.7 on 2023-03-04 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0019_loan_table_isapproved_alter_loan_table_paidamount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan_table',
            name='dueDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='loan_table',
            name='startDate',
            field=models.DateField(null=True),
        ),
    ]
