# Generated by Django 4.1.7 on 2023-03-13 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0020_alter_loan_table_duedate_alter_loan_table_startdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='loan_payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dates_to_pay', models.DateField(null=True)),
                ('paid', models.BooleanField(default=False)),
                ('loadId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan.loan_table')),
            ],
        ),
    ]
