# Generated by Django 4.1.7 on 2023-03-14 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0023_alter_loan_table_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrower_table',
            name='name',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='loan_table',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan.borrower_table'),
        ),
    ]
