# Generated by Django 4.1.7 on 2023-03-14 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0024_alter_borrower_table_name_alter_loan_table_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan_table',
            name='name',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
