# Generated by Django 4.1.7 on 2023-03-21 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0025_alter_loan_table_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan_payment',
            old_name='loadId',
            new_name='loanId',
        ),
        migrations.AddField(
            model_name='loan_payment',
            name='paid_dates',
            field=models.DateField(null=True),
        ),
    ]
