# Generated by Django 4.1.7 on 2023-03-22 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0026_rename_loadid_loan_payment_loanid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan_table',
            name='paidDates',
        ),
        migrations.AlterField(
            model_name='loan_table',
            name='daysLeft',
            field=models.IntegerField(default=0),
        ),
    ]
