# Generated by Django 4.1.7 on 2023-03-29 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0029_loan_manager_payment_request_staff_manager_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan_table',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='loan_table',
            name='staff',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
