# Generated by Django 4.1.7 on 2023-04-04 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0030_alter_loan_table_name_alter_loan_table_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment_request',
            name='date_request',
        ),
        migrations.AddField(
            model_name='payment_request',
            name='dates_request',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='payment_request',
            name='loan_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='payment_request',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
