# Generated by Django 4.1.7 on 2023-02-24 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='borrower_table',
        ),
    ]
